config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    get :search, on: :collection
  end

  resources :users
  root to: 'orders#index', as: :root

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
# frozen_string_literal: true
require 'order_id_generator'

class Order < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  enum service_type: %i[speed_post regular]
  enum payment_mode: %i[cod prepaid]
  enum status: {
    sent: 0,
    in_transit: 1,
    delivered: 2,
  }

  validates :service_type, presence: true
  validates :weight, presence: true
  validates :payment_mode, presence: true
  validates :service_cost, presence: true
  validates :sender_id, presence: true
  validates :receiver_id, presence: true

  validate :users_validation
  def users_validation
    if sender_id == receiver_id
      self.errors[:base] << "Sender and receiver can't be same!!!"
    end
  end

  after_create do
    self.order_id = OrderIdGenerator.get_order_id
    self.save!
  end

  before_save do
    if self.class.statuses[status] < self.class.statuses[status_was]
      self.errors[:base] << "Invalid Status!!!"
      raise_validation_error
    end
  end
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  has_many :orders

  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = if params[:order_id].present?
                Order.where(order_id: params[:order_id]).paginate(:page => 1, per_page: 1)
              else
                Order.paginate(:page => params[:page], per_page: 5)
              end
  end

  # GET /orders/1 or /orders/1.json
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    if Rails.env != 'production'
      host = "http://#{request.host}:#{request.port.to_s}"
    else
      host = "https://#{request.host}"
    end
    respond_to do |format|
      if @order.save
        UserMailer.with(order: @order, host: host).send_order_email.deliver_now
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    if Rails.env != 'production'
      host = "http://#{request.host}:#{request.port.to_s}"
    else
      host = "https://#{request.host}"
    end
    respond_to do |format|
      if @order.update(order_params)
        UserMailer.with(order: @order, host: host).send_updated_order_email.deliver_now
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:weight, :service_type, :service_cost, :payment_mode, :status, :sender_id, :receiver_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.paginate(:page => params[:page], :per_page=>5)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:full_name, :address, :mobile_number, :pin_code, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourierServices</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>

        * {
            text-decoration: none;
        }

      .menuContainer {
          background: #000;
          padding: 20px;
          border-radius: 10px;
          color: #fff;
      }
      .innerMenu {
          font-size: 20px;
          display: flex;
          justify-content: space-evenly;
      }

      .innerMenu a {
          color: #fff;
      }

      h1 {
          text-align: center;
          padding: 20px;
      }

        table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
        }

        table td, table th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        table tr:nth-child(even){background-color: #f2f2f2;}

        table tr:hover {background-color: #ddd;}

        table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #04AA6D;
            color: white;
        }

        form input {
            padding: 10px;
            border-radius: 10px;
        }

        select {
            padding: 8px;
            border-radius: 10px;
            width: 200px;
        }



    </style>
  </head>

  <body>
  <div class="menuContainer">
    <div class="innerMenu">
        <div href="#">Courier Services</div>
        <div>
          <%= link_to "Home", root_path, class: 'nav-link' %>
        </div>
        <div>
          <%= link_to "Orders", orders_path, class: 'nav-link' %>
        </div>
        <div>
          <%= link_to "Users", users_path, class: 'nav-link' %>
        </div>
      </div>
  </div>

  <div>
    <%= yield %>
  </div>


  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if order.order_id.present? %>
    <div class="field">
      <%= form.label :status %>
      <%= form.select :status, options_for_select(Order.statuses.map {|key, value| [key.titleize, Order.statuses.key(value)]}, order.status) %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weight, 'Weight (gms)' %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :service_type %>
    <%= form.select :service_type, options_for_select(Order.service_types.map {|key, value| [key.titleize, Order.service_types.key(value)]}, order.service_type) %>
  </div>

  <div class="field">
    <%= form.label :service_cost, 'Service Cost (INR)' %>
    <%= form.number_field :service_cost %>
  </div>

  <div class="field">
    <%= form.label :payment_mode %>
    <%= form.select :payment_mode, options_for_select(Order.payment_modes.map {|key, value| [key.upcase, Order.payment_modes.key(value)]}, order.payment_mode) %>  </div>
  </div>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.collection_select :sender_id, User.order(created_at: :desc), :id, :full_name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.collection_select :receiver_id, User.order(created_at: :desc), :id, :full_name, include_blank: false %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<a href="/users/new">Create Sender/Receiver</a>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>
<%= form_tag(orders_path, method: 'get') do %>
  <%= text_field_tag(:order_id, params[:order_id]) %>
  <%= submit_tag("Search By Order ID", name: nil) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Weight (gms)</th>
      <th>Service type</th>
      <th>Service cost (INR)</th>
      <th>Payment mode</th>
      <th>Status</th>
      <th>Sender</th>
      <th>Receiver</th>
      <th>Order ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.weight %></td>
        <td><%= order.service_type.titleize %></td>
        <td><%= order.service_cost %></td>
        <td><%= order.payment_mode.upcase %></td>
        <td><%= order.status.titleize %></td>
        <td><%= order.sender.email %></td>
        <td><%= order.receiver.email %></td>
        <td><%= order.order_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
<br><br>
<div class="test_pagination_orders">
  <div class="page_info_orders">
    <%= page_entries_info @orders %>
  </div>
  <%= will_paginate @orders, :container => false %>
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @order.weight %>
</p>

<p>
  <strong>Service type:</strong>
  <%= @order.service_type %>
</p>

<p>
  <strong>Service cost:</strong>
  <%= @order.service_cost %>
</p>

<p>
  <strong>Payment mode:</strong>
  <%= @order.payment_mode %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @order.sender.email %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @order.receiver.email %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%#= link_to 'Back', orders_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :mobile_number %>
    <%= form.text_field :mobile_number %>
  </div>

  <div class="field">
    <%= form.label :pin_code %>
    <%= form.text_field :pin_code %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Address</th>
      <th>Mobile number</th>
      <th>Pin code</th>
      <th>Email ID</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.address %></td>
        <td><%= user.mobile_number %></td>
        <td><%= user.pin_code %></td>
        <td><%= user.email%></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<br><br>
<div class="test_pagination_users">
  <div class="page_info_users">
    <%= page_entries_info @posts %>
  </div>
  <%= will_paginate @posts, :container => false %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @user.mobile_number %>
</p>

<p>
  <strong>Pin code:</strong>
  <%= @user.pin_code %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>